services:
    rusty:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: rusty
      #tty: true
      environment:
        - EDITOR: /usr/bin/hx
        - HOME: /root
        - SHELL: /bin/bash
      volumes:
        - ./root:/root:rw

